services:
  python:
    container_name: python-innopolis
    restart: unless-stopped
    image: python:3.14-slim
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python -m http.server 8000
#    command: python src/init.py